### ISSUE TITLE
Getting "invalid port value" from TCPStream::connect in TevClient::spawn

### ISSUE THREAD

**Issue by smukherjee2016** [KarelPeeters/tev_client#1]
Hi, thanks so much for developing this library! 

Actually, I am unable to use it to run tev inside my program. The `TCPStream::connect()` call in `TevClient::spawn()` returns the following error:

> Error: Error { kind: InvalidInput, message: "invalid port value" }

However, manually setting `host` to `127.0.0.1:14158` just before the `connect()` call appears to work.

Could you please take a look? Thanks!

**Comment by KarelPeeters** [comment]
Hmm everything still works for me on the latest release of _tev_ (`1.17`). Are you using either an old or self-build version?

I've published a new version of `tev_client` (`0.4.0`) that includes some more information in the error returned by `spawn`, could you try again and see what it says?

**Comment by smukherjee2016** [comment]
Thanks for the response!

Actually, I built the latest version of the `tev` repository myself, so maybe something changed between `1.17` and the latest code.

Here is the output of the error with `0.4.0`:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Tcp { host: "127.0.0.1:14158\u{1b}[K\u{1b}[0m", io: Error { kind: InvalidInput, message: "invalid port value" } }'

Those extra characters at the end after `14158` look suspicious...

**Comment by KarelPeeters** [comment]
The characters `\u001b[0m` reset the terminal font color, but that should only happen after the printed line is finished.

I tried building the latest _tev_ master myself and it still works. What exact commit are you using? If you run the tev binary yourself does the output look something like this?

![image](https://user-images.githubusercontent.com/7887115/138857721-d88f7840-88c9-45b7-b0d6-c5b59a8fdb00.png)

**Comment by smukherjee2016** [comment]
I'm sorry for the late reply! 

Yup, the output looks exactly like your screenshot when I launch `tev`!

However, I found a couple of things:

- It seems the crash **only happens in Linux** (or atleast, Linux Mint 20.2 which is based on Ubuntu 20.04 LTS). I tried running the same codebase on Windows and it works perfectly. I don't have a Mac so I cannot check that, unfortunately.
- Also, it seems `tev` gets launched properly when a `let mut client = TevClient::spawn_path_default().unwrap();` is in the parent codebase. Apologies for not making it clear. However, the parent program crashes on that `unwrap()`.

It seems weird that it'd only crash on Linux... Please let me know what else I can do to help!

**Comment by KarelPeeters** [comment]
Aha, Linux! It seems like the logger library appends some extra stuff for terminals that support more escape sequences, specifically here: https://github.com/Tom94/tinylogger/blob/9b7a92ff44ffca3e80dca3549fa4eb599d039eeb/tinylogger/tinylogger.h#L264-L273.

I've fixed this by cutting off the rest of the log line starting from the `\u{1b}` escape character. It seems to work for me on Linux now. Can you check to make sure?

**Comment by smukherjee2016** [comment]
Thanks for the quick reply! 

Yup, I checked with the fixes and it works without crashing. I'll pull in the latest version into my codebase once you make a release!

Thanks again!

**Comment by KarelPeeters** [comment]
Ah right thanks for the reminder! I just released version ~~`0.5.0`~~ `0.5.1`. Good luck with this crate!
